# Generated by Django 3.2 on 2022-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_data', '0002_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_no',
            field=models.FloatField(),
        ),
    ]
